# Generated by Django 3.2.5 on 2021-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_testcase_testresult_testtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='error',
            field=models.IntegerField(default=0, verbose_name='错误用例'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='failure',
            field=models.IntegerField(default=0, verbose_name='失败用例'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='run_time',
            field=models.FloatField(default=0, verbose_name='运行时长'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='skipped',
            field=models.IntegerField(default=0, verbose_name='跳过用例'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='tests',
            field=models.IntegerField(default=0, verbose_name='总用例数'),
        ),
    ]
